service: serverless-url-shortener

provider:
  name: aws
  endpointType: ${file(config.json):API_ENDPOINT_TYPE}
  runtime: nodejs8.10
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:${file(config.json):S3_PARTITION}:s3:::${file(config.json):DOMAIN_NAME}/*"

functions:
  store:
    handler: api/store.handle
    events:
      - http:
          path: /
          method: post
          cors: true

resources:
  Resources:
    ServerlesslyRedirectS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(config.json):DOMAIN_NAME}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - POST
            - PUT
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"
        WebsiteConfiguration:
          IndexDocument: index.html
    ServerlesslyRedirectS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${file(config.json):DOMAIN_NAME}
        PolicyDocument:
          Statement:
          - Action:
            - s3:GetObject
            Effect: Allow
            Resource:
            - arn:${file(config.json):S3_PARTITION}:s3:::${file(config.json):DOMAIN_NAME}/*
            Principal: "*"
    CDN:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases: ${file(config.json):DOMAIN_ALIASES}
          PriceClass: PriceClass_100
          ViewerCertificate:
            AcmCertificateArn: ${file(config.json):CERTIFICATE_ARN}
            SslSupportMethod: sni-only
          Enabled: true
          HttpVersion: http2
          DefaultRootObject: index.html
          Origins:
            - DomainName: ${file(config.json):DOMAIN_NAME}.s3-website-${file(config.json):REGION}.amazonaws.com
              Id: S3Origin
              CustomOriginConfig:
                OriginProtocolPolicy: http-only
          DefaultCacheBehavior:
            ViewerProtocolPolicy: redirect-to-https
            TargetOriginId: S3Origin
            AllowedMethods:
              - GET
              - HEAD
            Compress: false
            ForwardedValues:
              QueryString: true
